import {useEffect} from 'react';import {useStore} from '../store';import {X,Star,Trash2,Code2,Pin,RefreshCw,Clock} from 'lucide-react';import {motion,AnimatePresence} from 'framer-motion';
export function SnippetsPanel(){const{showSnippets,setShowSnippets,dbSnippets,dbLoading,loadDb,loadSnippetToEditor,removeSnippet,togglePin,activeFile,saveSnippetFromFile}=useStore();
useEffect(()=>{if(showSnippets)loadDb();},[showSnippets]);if(!showSnippets)return null;const file=activeFile();
return(<AnimatePresence><motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 flex items-center justify-center" style={{background:'rgba(0,0,0,0.6)',backdropFilter:'blur(6px)'}} onClick={()=>setShowSnippets(false)}>
<motion.div initial={{scale:0.95}} animate={{scale:1}} exit={{scale:0.95}} className="flex h-[540px] max-h-[90vh] w-[620px] max-w-[95vw] flex-col rounded-2xl border border-cv-border shadow-2xl bg-cv-surface" onClick={e=>e.stopPropagation()}>
<div className="flex shrink-0 items-center justify-between border-b border-cv-border px-5 py-3"><div className="flex items-center gap-2"><Code2 size={15} className="text-cv-accent"/><h2 className="text-sm font-semibold text-cv-text">Snippets</h2><span className="rounded-full bg-cv-accent/20 px-2 py-0.5 text-[10px] font-medium text-cv-accent">{dbSnippets.length}</span></div><div className="flex items-center gap-2">{file&&<button onClick={()=>saveSnippetFromFile(file.id)} className="rounded-lg bg-cv-accent px-3 py-1.5 text-xs font-semibold text-white hover:opacity-90">Save Current</button>}<button onClick={loadDb} className="ib"><RefreshCw size={12}/></button><button onClick={()=>setShowSnippets(false)} className="ib"><X size={14}/></button></div></div>
<div className="flex-1 overflow-y-auto p-4">{dbLoading&&<p className="py-10 text-center text-xs text-cv-muted">Loading…</p>}{!dbLoading&&dbSnippets.length===0&&<div className="flex flex-col items-center py-12"><Code2 size={32} className="text-cv-muted opacity-30"/><p className="mt-3 text-sm text-cv-muted">No snippets yet</p></div>}
<div className="grid grid-cols-1 gap-2 sm:grid-cols-2">{dbSnippets.map(sn=>(<div key={sn.id} className="rounded-xl border border-cv-border bg-cv-elevated p-3 hover:border-cv-accent/50 transition-all"><div className="flex items-start justify-between gap-2"><div className="flex-1 min-w-0"><div className="flex items-center gap-1.5">{sn.is_pinned&&<Pin size={9} className="text-cv-warning"/>}<p className="truncate text-xs font-semibold text-cv-text">{sn.name}</p></div><div className="mt-1 flex gap-2 text-[9px] text-cv-muted"><span>{sn.language}</span><span>·</span><span>{sn.run_count} runs</span></div></div><div className="flex shrink-0 gap-0.5"><button onClick={()=>togglePin(sn.id)} className={`ib !p-1 ${sn.is_pinned?'!text-cv-warning':''}`}><Star size={11}/></button><button onClick={()=>{loadSnippetToEditor(sn);setShowSnippets(false);}} className="ib !p-1 !text-cv-accent"><Code2 size={11}/></button><button onClick={()=>removeSnippet(sn.id)} className="ib !p-1 hover:!text-red-400"><Trash2 size={11}/></button></div></div><pre className="mt-2 max-h-14 overflow-hidden rounded-md bg-cv-surface p-1.5 text-[10px] text-cv-muted">{(sn.content||'').slice(0,200)}</pre></div>))}</div></div>
</motion.div></motion.div></AnimatePresence>);}

export function HistoryPanel(){const{showHistory,setShowHistory,dbHistory,dbLoading,loadDb,removeHistory,wipeHistory,loadSnippetToEditor,dbSnippets}=useStore();
useEffect(()=>{if(showHistory)loadDb();},[showHistory]);if(!showHistory)return null;
const fmt=(s:string)=>{const d=new Date(s),now=new Date(),diff=(now.getTime()-d.getTime())/1000;if(diff<60)return`${Math.round(diff)}s ago`;if(diff<3600)return`${Math.round(diff/60)}m ago`;return d.toLocaleDateString();};
return(<AnimatePresence><motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 flex items-center justify-center" style={{background:'rgba(0,0,0,0.6)',backdropFilter:'blur(6px)'}} onClick={()=>setShowHistory(false)}>
<motion.div initial={{scale:0.95}} animate={{scale:1}} exit={{scale:0.95}} className="flex h-[540px] max-h-[90vh] w-[680px] max-w-[95vw] flex-col rounded-2xl border border-cv-border shadow-2xl bg-cv-surface" onClick={e=>e.stopPropagation()}>
<div className="flex shrink-0 items-center justify-between border-b border-cv-border px-5 py-3"><div className="flex items-center gap-2"><Clock size={15} className="text-cv-accent"/><h2 className="text-sm font-semibold text-cv-text">Run History</h2><span className="rounded-full bg-cv-accent/20 px-2 py-0.5 text-[10px] font-medium text-cv-accent">{dbHistory.length}</span></div><div className="flex items-center gap-2">{dbHistory.length>0&&<button onClick={wipeHistory} className="flex items-center gap-1.5 rounded-lg border border-cv-error/30 px-3 py-1.5 text-xs text-cv-error hover:bg-cv-error/10"><Trash2 size={11}/> Clear</button>}<button onClick={loadDb} className="ib"><RefreshCw size={12}/></button><button onClick={()=>setShowHistory(false)} className="ib"><X size={14}/></button></div></div>
<div className="flex-1 overflow-y-auto p-4">{dbLoading&&<p className="py-10 text-center text-xs text-cv-muted">Loading…</p>}{!dbLoading&&dbHistory.length===0&&<div className="flex flex-col items-center py-12"><Clock size={32} className="text-cv-muted opacity-30"/><p className="mt-3 text-sm text-cv-muted">No history yet</p></div>}
<div className="space-y-2">{dbHistory.map(h=>{const snip=h.snippet_id?dbSnippets.find(s=>s.id===h.snippet_id):null;return(<div key={h.id} className="rounded-xl border border-cv-border bg-cv-elevated p-3"><div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2"><span className={`h-2 w-2 rounded-full ${h.exit_code===0?'bg-cv-success':'bg-cv-error'}`}/><span className="text-xs font-medium text-cv-text">{snip?.name??'Unsaved'}</span></div><div className="flex items-center gap-1 text-[10px] text-cv-muted"><span>{h.duration_ms}ms</span><span>·</span><span>{fmt(h.created_at)}</span><button onClick={()=>{loadSnippetToEditor({id:h.id,name:'history.py',content:h.code,language:'python',description:'',is_pinned:false,run_count:0,last_run_at:null,created_at:h.created_at,updated_at:h.created_at});setShowHistory(false);}} className="ib !p-0.5 ml-1"><Code2 size={10}/></button><button onClick={()=>removeHistory(h.id)} className="ib !p-0.5 hover:!text-red-400"><Trash2 size={10}/></button></div></div>{h.error_message&&<p className="mt-1 truncate text-[10px] text-cv-error">{h.error_message}</p>}<pre className="mt-1 max-h-10 overflow-hidden text-[10px] text-cv-muted">{(h.code||'').split('\n').slice(0,3).join('\n')}</pre></div>);})}</div></div>
</motion.div></motion.div></AnimatePresence>);}
