import {useState} from 'react';import {useStore,DEF_CFG} from '../store';import {THEMES,FONTS,ACCENT_COLORS} from '../themes';import {X,Check,RotateCcw,Palette,Code,Sliders} from 'lucide-react';import {motion,AnimatePresence} from 'framer-motion';
const CATS=[{id:'look',label:'Appearance',Icon:Palette},{id:'edit',label:'Editor',Icon:Code},{id:'feat',label:'Features',Icon:Sliders}] as const;
function Tog({label,value,onChange}:{label:string;value:boolean;onChange(v:boolean):void}){return <button onClick={()=>onChange(!value)} className="flex w-full items-center justify-between rounded-lg px-2 py-1.5 text-xs hover:bg-white/5 transition-colors"><span className="text-cv-text">{label}</span><div className={`flex h-5 w-9 items-center rounded-full p-0.5 transition-colors ${value?'bg-cv-accent':'bg-cv-border'}`}><div className={`h-4 w-4 rounded-full bg-white shadow transition-transform ${value?'translate-x-4':''}`}/></div></button>;}
function Rng({label,min,max,value,onChange}:{label:string;min:number;max:number;value:number;onChange(v:number):void}){return <div><label className="mb-1.5 block text-xs font-medium text-cv-muted">{label}</label><input type="range" min={min} max={max} value={value} onChange={e=>onChange(+e.target.value)} className="w-full accent-cv-accent"/></div>;}
export function SettingsModal(){const {showCfg,setShowCfg,cfg,updateCfg,notify}=useStore();const [cat,setCat]=useState<typeof CATS[number]['id']>('look');if(!showCfg)return null;
return(<AnimatePresence><motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 flex items-center justify-center" style={{background:'rgba(0,0,0,0.6)',backdropFilter:'blur(6px)'}} onClick={()=>setShowCfg(false)}><motion.div initial={{scale:0.95}} animate={{scale:1}} exit={{scale:0.95}} className="flex h-[520px] max-h-[90vh] w-[660px] max-w-[95vw] flex-col overflow-hidden rounded-2xl border border-cv-border shadow-2xl bg-cv-surface" onClick={e=>e.stopPropagation()}>
<div className="flex items-center justify-between border-b border-cv-border px-5 py-3"><h2 className="text-sm font-semibold text-cv-text">Settings</h2><button onClick={()=>setShowCfg(false)} className="ib"><X size={14}/></button></div>
<div className="flex flex-1 overflow-hidden"><div className="w-36 shrink-0 border-r border-cv-border p-2">{CATS.map(c=><button key={c.id} onClick={()=>setCat(c.id)} className={`flex w-full items-center gap-2 rounded-lg px-3 py-2 text-xs transition-colors ${cat===c.id?'bg-cv-accent/15 text-cv-text':'text-cv-muted hover:bg-white/5 hover:text-cv-text'}`}><c.Icon size={12}/>{c.label}</button>)}</div>
<div className="flex-1 space-y-4 overflow-y-auto p-5">
{cat==='look'&&<><div><label className="mb-1.5 block text-xs font-medium text-cv-muted">Theme</label><div className="grid grid-cols-2 gap-1.5 sm:grid-cols-3">{THEMES.map(t=><button key={t.id} onClick={()=>updateCfg({theme:t.id})} className={`flex items-center gap-2 rounded-lg border px-2 py-1.5 text-xs transition-all ${cfg.theme===t.id?'border-cv-accent bg-cv-accent/10':'border-cv-border hover:border-cv-muted'}`}><div className="h-4 w-4 shrink-0 rounded-full border border-cv-border/50" style={{background:t.bg}}/><span className="truncate text-cv-text">{t.name}</span>{cfg.theme===t.id&&<Check size={9} className="ml-auto text-cv-accent"/>}</button>)}</div></div><div><label className="mb-1.5 block text-xs font-medium text-cv-muted">Accent</label><div className="flex flex-wrap gap-2">{ACCENT_COLORS.map(c=><button key={c.value} onClick={()=>updateCfg({accent:c.value})} title={c.name} className={`h-7 w-7 rounded-full border-2 transition-transform hover:scale-110 ${cfg.accent===c.value?'border-white scale-110':'border-transparent'}`} style={{background:c.value}}/>)}<input type="color" value={cfg.accent} onChange={e=>updateCfg({accent:e.target.value})} className="h-7 w-7 cursor-pointer rounded-full border-2 border-cv-border bg-transparent"/></div></div></>}
{cat==='edit'&&<><Rng label={`Font Size: ${cfg.fontSize}px`} min={8} max={36} value={cfg.fontSize} onChange={v=>updateCfg({fontSize:v})}/><Rng label={`Zoom: ${cfg.zoom}%`} min={50} max={300} value={cfg.zoom} onChange={v=>updateCfg({zoom:v})}/><Rng label={`Terminal Font: ${cfg.termFont}px`} min={8} max={24} value={cfg.termFont} onChange={v=>updateCfg({termFont:v})}/><div><label className="mb-1.5 block text-xs font-medium text-cv-muted">Font</label><select value={cfg.font} onChange={e=>updateCfg({font:e.target.value})} className="ci w-full">{FONTS.map(f=><option key={f} value={f}>{f}</option>)}</select></div><div><label className="mb-1.5 block text-xs font-medium text-cv-muted">Tab Size</label><select value={cfg.tabSize} onChange={e=>updateCfg({tabSize:+e.target.value})} className="ci w-full">{[2,4,8].map(n=><option key={n} value={n}>{n} spaces</option>)}</select></div></>}
{cat==='feat'&&<><Tog label="Word Wrap" value={cfg.wordWrap} onChange={v=>updateCfg({wordWrap:v})}/><Tog label="Minimap" value={cfg.minimap} onChange={v=>updateCfg({minimap:v})}/><Tog label="Line Numbers" value={cfg.lineNumbers} onChange={v=>updateCfg({lineNumbers:v})}/><Tog label="Code Folding" value={cfg.folding} onChange={v=>updateCfg({folding:v})}/><Tog label="Quick Suggestions" value={cfg.quickSuggest} onChange={v=>updateCfg({quickSuggest:v})}/><Tog label="Auto Save" value={cfg.autoSave} onChange={v=>updateCfg({autoSave:v})}/><Tog label="Font Ligatures" value={cfg.fontLigatures} onChange={v=>updateCfg({fontLigatures:v})}/></>}
</div></div>
<div className="flex items-center justify-between border-t border-cv-border px-5 py-3"><button onClick={()=>{updateCfg(DEF_CFG);notify({level:'success',title:'Reset to defaults'});}} className="flex items-center gap-1.5 rounded-lg px-3 py-1.5 text-xs text-cv-error hover:bg-cv-error/10 transition-colors"><RotateCcw size={11}/> Reset</button><button onClick={()=>setShowCfg(false)} className="rounded-lg bg-cv-accent px-4 py-1.5 text-xs font-semibold text-white hover:opacity-90">Done</button></div>
</motion.div></motion.div></AnimatePresence>);}
